In [1]:
import pandas as pd
import os

In [16]:
customers = pd.read_csv(r"C:\Users\Asus\Desktop\customer_prediction\data\raw\customers_dataset.csv")
items = pd.read_csv(r"C:\Users\Asus\Desktop\customer_prediction\data\raw\items_dataset.csv")
orders = pd.read_csv(r"C:\Users\Asus\Desktop\customer_prediction\data\raw\orders_dataset.csv")
payments = pd.read_csv(r"C:\Users\Asus\Desktop\customer_prediction\data\raw\payments_dataset.csv")
reviews = pd.read_csv(r"C:\Users\Asus\Desktop\customer_prediction\data\raw\reviews_dataset.csv")
sellers = pd.read_csv(r"C:\Users\Asus\Desktop\customer_prediction\data\raw\sellers_dataset.csv")

In [3]:
customers.head(20)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR
9,4b7139f34592b3a31687243a302fa75b,9afe194fb833f79e300e37e580171f22,30575,belo horizonte,MG
10,9fb35e4ed6f0a14a4977cd9aea4042bb,2a7745e1ed516b289ed9b29c7d0539a5,39400,montes claros,MG
11,5aa9e4fdd4dfd20959cad2d772509598,2a46fb94aef5cbeeb850418118cee090,20231,rio de janeiro,RJ
12,b2d1536598b73a9abd18e0d75d92f0a3,918dc87cd72cd9f6ed4bd442ed785235,18682,lencois paulista,SP
13,eabebad39a88bb6f5b52376faec28612,295c05e81917928d76245e842748184d,5704,sao paulo,SP
14,1f1c7bf1c9b041b292af6c1c4470b753,3151a81801c8386361b62277d7fa5ecf,95110,caxias do sul,RS
15,206f3129c0e4d7d0b9550426023f0a08,21f748a16f4e1688a9014eb3ee6fa325,13412,piracicaba,SP
16,a7c125a0a07b75146167b7f04a7f8e98,5c2991dbd08bbf3cf410713c4de5a0b5,22750,rio de janeiro,RJ
17,c5c61596a3b6bd0cee5766992c48a9a1,b6e99561fe6f34a55b0b7da92f8ed775,7124,guarulhos,SP
18,9b8ce803689b3562defaad4613ef426f,7f3a72e8f988c6e735ba118d54f47458,5416,sao paulo,SP
19,49d0ea0986edde72da777f15456a0ee0,3e6fd6b2f0d499456a6a6820a40f2d79,68485,pacaja,PA

In [17]:
customers.info()
customers.shape
customers.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [18]:
customers["customer_unique_id"].nunique()

96096

In [19]:
customers["customer_id"].nunique()

99441

In [20]:
orders.info()
orders.shape

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 20.5 MB

(99441, 8)

In [12]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [22]:
orders["order_purchase_timestamp"].head()

0    02-10-2017 10:56
1    24-07-2018 20:41
2    08-08-2018 08:38
3    18-11-2017 19:28
4    13-02-2018 21:18
Name: order_purchase_timestamp, dtype: str

In [21]:
orders["order_purchase_timestamp"].min(), orders["order_purchase_timestamp"].max()

('01-01-2018 02:48', '31-12-2017 23:29')

In [23]:
orders["order_id"].nunique()
orders["customer_id"].nunique()
orders.groupby("customer_id").size().value_counts().head()

1    99441
Name: count, dtype: int64

In [24]:
customer_orders = orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)
customer_orders["customer_unique_id"].nunique()
customer_orders["customer_unique_id"].value_counts().head(10)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
ca77025e7201e3b30c44b472ff346268     7
1b6c7548a2a1f9037c1fd3ddfed95f33     7
6469f99c1f9dfae7733b25662e7f1782     7
12f5d6e1cbf93dafd9dcc19095df0b3d     6
de34b16117594161a6a89c50b289d35a     6
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
f0e310a6839dce9de1638e0fe5ab282a     6
dc813062e0fc23409cd255f7f53c7074     6
Name: count, dtype: int64

In [25]:
orders_per_customer = (
    customer_orders
    .groupby("customer_unique_id")
    .size()
)

orders_per_customer.describe()
orders_per_customer.head()

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    1
0000b849f77a49e4a4ce2b2a4ca5be3f    1
0000f46a3911fa3c0805444483337064    1
0000f6ccb0745a6a4b88665a16c9f078    1
0004aac84e0df4da2b147fca70cf8255    1
dtype: int64

In [26]:
orders_per_customer.sort_values(ascending=False).head(10)

total_customers = orders_per_customer.shape[0]
repeat_customers = (orders_per_customer > 1).sum()
repeat_percentage = repeat_customers / total_customers * 100
repeat_customers, total_customers, repeat_percentage

(np.int64(2997), 96096, np.float64(3.1187562437562435))

In [27]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 20.5 MB

In [28]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 8.1 MB

In [29]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [30]:
payments["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [31]:
payments['payment_value'].sort_values(ascending=False).head()

52107    13664.08
34370     7274.88
41419     6929.31
49581     6922.21
85539     6726.66
Name: payment_value, dtype: float64

In [32]:
payments['payment_value'].head()

0     99.33
1     24.39
2     65.71
3    107.78
4    128.45
Name: payment_value, dtype: float64

In [33]:
payments["payment_installments"].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

In [34]:
items.info()
items.shape

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 18.4 MB

(112650, 7)

In [35]:
datasets = {
    "customers": customers,
    "orders": orders,
    "items": items,
    "payments": payments,
    "products": products,
    "reviews": reviews,
    "sellers": sellers
}

for name, df in datasets.items():
    print(f"\n===== {name.upper()} =====")
    print("Shape:", df.shape)
    print("Duplicate rows:", df.duplicated().sum())
    print("Missing values:")
    print(df.isnull().sum())

===== CUSTOMERS =====
Shape: (99441, 5)
Duplicate rows: 0
Missing values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

===== ORDERS =====
Shape: (99441, 8)
Duplicate rows: 0
Missing values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

===== ITEMS =====
Shape: (112650, 7)
Duplicate rows: 0
Missing values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

===== PAYMENTS =====
Shape: (103886, 5)
Duplicate rows: 0
Missing values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

===== PRODUCTS =====
Shape: (32951, 9)
Duplicate rows: 0
Missing values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

===== REVIEWS =====
Shape: (99224, 7)
Duplicate rows: 0
Missing values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

===== SELLERS =====
Shape: (3095, 4)
Duplicate rows: 0
Missing values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [36]:
orders[orders['order_approved_at'].isna()]['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [37]:
orders['order_status'].value_counts()
orders[orders['order_delivered_carrier_date'].isna()]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [38]:
orders[orders['order_delivered_customer_date'].isna()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [39]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [41]:
###create new table for customers and finding now first and last purchase
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"],
    format="mixed"
)
orders_customer = orders.merge(
    customers[['customer_id', 'customer_unique_id']],
    on='customer_id',
    how='left'
)

df1 = (
    orders_customer
    .groupby('customer_unique_id')
    .agg(
        total_orders=('order_id', 'nunique'),
        first_purchase=('order_purchase_timestamp', 'min'),
        last_purchase=('order_purchase_timestamp', 'max')
    )
    .reset_index()
)

df1.head()

,customer_unique_id,total_orders,first_purchase,last_purchase
0,0000366f3b9a7992bf8c76cfdf3221e2,1,2018-10-05 10:56:00,2018-10-05 10:56:00
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,2018-07-05 11:11:00,2018-07-05 11:11:00
2,0000f46a3911fa3c0805444483337064,1,2017-10-03 21:05:00,2017-10-03 21:05:00
3,0000f6ccb0745a6a4b88665a16c9f078,1,2017-12-10 20:29:00,2017-12-10 20:29:00
4,0004aac84e0df4da2b147fca70cf8255,1,2017-11-14 19:45:00,2017-11-14 19:45:00

In [42]:
df1.shape

(96096, 4)

In [43]:
###repeat customer findings
repeat_customers = df1[df1['total_orders'] > 1]

repeat_customers.shape
repeat_percentage = len(repeat_customers) / len(df1) * 100

repeat_percentage

3.1187562437562435

In [44]:
df1['total_orders'].value_counts().sort_index()

total_orders
1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [45]:
###Revenue analysis

payment_type_summary = (
    payments.groupby('payment_type')['payment_value']
    .agg(
        total='sum',
        average='mean',
        count='count'
    )
    .sort_values('total', ascending=False)
    .reset_index()
)

payment_type_summary.to_csv(
    r"C:\Users\Asus\Desktop\customer_prediction\data\processed\payment_type_revenue.csv",
    index=False
)

In [46]:
##order status checking and calculating
order_status_summary = (
    orders.groupby('order_status')['order_id']
    .count()
    .reset_index(name='order_count')
)

order_status_summary['percentage'] = (
    order_status_summary['order_count']
    / order_status_summary['order_count'].sum()
    * 100
)

order_status_summary = order_status_summary.sort_values(
    'order_count',
    ascending=False
)

order_status_summary.to_csv(
    r"C:\Users\Asus\Desktop\customer_prediction\data\processed\order_status_summary.csv",
    index=False
)

In [47]:
####review analysis
review_analysis = (
    reviews
    .groupby('review_score')
    .agg(
        review_count=('review_id', 'count'),
        avg_score=('review_score', 'mean')
    )
    .sort_index()
)

review_analysis
reviews['review_score'].value_counts().sort_index()
review_analysis.to_csv(
    'C:/Users/Asus/Desktop/customer_prediction/data/processed/review_analysis.csv',
    index=False
)

In [49]:
orders["year"] = orders["order_purchase_timestamp"].dt.year
orders["month"] = orders["order_purchase_timestamp"].dt.month

In [50]:
###yearly sales
yearly_sales = (
    orders.groupby('year')['order_id']
    .nunique()
)

yearly_sales

year
2016      329
2017    45101
2018    54011
Name: order_id, dtype: int64

In [51]:
###monthly sales
monthly_sales = (
    orders.groupby(['year', 'month'])['order_id']
    .nunique()
    .reset_index(name='total_orders')
)

monthly_sales

    year  month  total_orders
0   2016      2             1
1   2016      3             8
2   2016      4            64
3   2016      5            48
4   2016      6            51
5   2016      7            46
6   2016      8            42
7   2016      9            28
8   2016     10            40
9   2016     12             1
10  2017      1          2116
11  2017      2          2201
12  2017      3          3065
13  2017      4          2933
14  2017      5          3821
15  2017      6          3369
16  2017      7          3930
17  2017      8          4027
18  2017      9          3975
19  2017     10          4241
20  2017     11          7215
21  2017     12          4208
22  2018      1          6258
23  2018      2          5987
24  2018      3          6254
25  2018      4          6102
26  2018      5          5442
27  2018      6          5549
28  2018      7          6325
29  2018      8          4985
30  2018      9          1884
31  2018     10          1715
32  2018     11          1787
33  2018     12          1723

In [54]:
from scipy.stats import chi2_contingency

table = pd.crosstab(
    payments["payment_type"],
    payments["payment_installments"]
)

chi2, p_value, dof, expected = chi2_contingency(table)

print("Chi-square:", chi2)
print("P-value:", p_value)

if p_value < 0.05:
    print("Reject H0: Payment type and number of installments are associated.")
else:
    print("Fail to reject H0: No significant association.")

Chi-square: 35806.78421329059
P-value: 0.0
Reject H0: Payment type and number of installments are associated.

In [48]:

df1.to_csv(
    'C:/Users/Asus/Desktop/customer_prediction/data/processed/customer_analysis.csv',
    index=False
)